### ISSUE TITLE
Back end: to-do-list

### ISSUE THREAD

**Issue by Laerolf** [Laerolf/Abbey#1]
- [ ] Merge stock and tasklist of Game.js
- [ ] Implement local storage
- [ ] Make a class for a process bar -> connected to a task its processtime
