### ISSUE TITLE
Front end: to-do-list

### ISSUE THREAD

**Issue by Laerolf** [Laerolf/Abbey#2]
- [ ] Rebuild website -> bootstrap doesn't mean a lot of divs
- [ ] Fix the processbars
- [ ] Check if the website is responsive
- [ ] The background shouldn't be moving if you open certain tabs
